;; Mindenfele kornyezet - tetel, s tarsai
(global-set-key "\C-ct1" '(lambda ()
                         (interactive)
			 (message "Inserting: TETEL")
			 (insert "" "\\begin{te}\n  \n\\end{te}\n")
			 (forward-line -2)
			 (forward-char 2)
			 ))
(global-set-key "\C-ct2" '(lambda ()
                         (interactive)
			 (message "Inserting: DEFINICIO")
			 (insert "" "\\begin{de}\n  \n\\end{de}\n")
			 (forward-line -2)
			 (forward-char 2)
			 ))
(global-set-key "\C-ct3" '(lambda ()
                         (interactive)
			 (message "Inserting: LEMMA")
			 (insert "" "\\begin{lemma}\n  \n\\end{lemma}\n")
			 (forward-line -2)
			 (forward-char 2)
			 ))
(global-set-key "\C-ct4" '(lambda ()
                         (interactive)
			 (message "Inserting: BIZONYITAS")
			 (insert "" "\\begin{biz}\n  \n\\end{biz}\n")
			 (forward-line -2)
			 (forward-char 2)
			 ))
(global-set-key "\C-ct5" '(lambda ()
                         (interactive)
			 (message "Inserting: KOVETKEZMENY")
			 (insert "" "\\begin{kov}\n  \n\\end{kov}\n")
			 (forward-line -2)
			 (forward-char 2)
			 ))
(global-set-key "\C-ct6" '(lambda ()
                         (interactive)
			 (message "Inserting: MEGJEGYZES")
			 (insert "" "\\begin{megj}\n  \n\\end{megj}\n")
			 (forward-line -2)
			 (forward-char 2)
			 ))
(global-set-key "\C-ct8" '(lambda ()
                         (interactive)
			 (message "Inserting: BIZONYITAS - Körözött")
			 (insert "" "\\begin{Biz}\n  \n\\end{Biz}\n")
			 (forward-line -2)
			 (forward-char 2)
			 ))
(global-set-key "\C-ct9" '(lambda ()
                         (interactive)
			 (message "Inserting: MEGJEGYZES - Körözött")
			 (insert "" "\\begin{Megj}\n  \n\\end{Megj}\n")
			 (forward-line -2)
			 (forward-char 2)
			 ))

;; felsorolasok
(global-set-key "\C-ctr" '(lambda ()
                         (interactive)
			 (message "Inserting: ENUM ZJEL ROMAI")
			 (insert "" "\\begin{enumzjr}\n  \\item \n\\end{enumzjr}\n")
			 (forward-line -2)
			 (forward-char 8)
			 ))
(global-set-key "\C-ctb" '(lambda ()
                         (interactive)
			 (message "Inserting: ENUM ZJEL BETU")
			 (insert "" "\\begin{enumzjr}\n  \\item \n\\end{enumzjr}\n")
			 (forward-line -2)
			 (forward-char 8)
			 ))
(global-set-key "\C-ctn" '(lambda ()
                         (interactive)
			 (message "Inserting: ENUMERATE")
			 (insert "" "\\begin{enumerate}\n  \\item \n\\end{enumerate}\n")
			 (forward-line -2)
			 (forward-char 8)
			 ))
(global-set-key "\C-ctI" '(lambda ()
                         (interactive)
			 (message "Inserting: ENUMERATE")
			 (insert "" "\\begin{itemize}\n  \\item \n\\end{itemize}\n")
			 (forward-line -2)
			 (forward-char 8)
			 ))
(global-set-key "\C-ctl" '(lambda ()
                         (interactive)
			 (message "Inserting: bizlist")
			 (insert "" "\\begin{bizlist}\n  \\item \n\\end{bizlist}\n")
			 (forward-line -2)
			 (forward-char 8)
			 ))
(global-set-key "\C-cti" '(lambda ()
                         (interactive)
			 (message "Inserting: ENUM ITEM")
			 (insert "" "\n  \\item ")
			 ))
;; egyeb
;(global-set-key "\C-ctc" '(lambda ()
;                         (interactive)
;			 (message "Inserting: C to C (functions)")
;			 (insert "" "\\C\\to\\C")))
(global-set-key "\C-ctd" '(lambda ()
                         (interactive)
			 (message "Inserting: dfrac")
			 (insert "" "\\dfrac{}{}")
			 (forward-char -3)
			 ))
(global-set-key "\C-ctg" '(lambda ()
                         (interactive)
			 (message "Inserting: GATHER*")
			 (insert "" "\\begin{gather*}\n  \n\\end{gather*}\n")
			 (forward-line -2)
			 (forward-char 2)
			 ))
(global-set-key "\C-ctq" '(lambda ()
                         (interactive)
			 (message "Inserting: QUAD")
			 (insert "" "\\quad ")
			 ))

(global-set-key "\C-cth" '(lambda ()
                         (interactive)
			 (message "Inserting: SET")
			 (insert "" "\\{\\, : \\,\\}")
			 (forward-char -6)
			 ))
(global-set-key "\C-ctm" '(lambda ()
                         (interactive)
			 (message "Inserting: bMATRIX")
			 (insert "" "\\begin{bmatrix}  \\end{bmatrix}")
			 (forward-char -14)
			 ))

(global-set-key "\C-ctc" '(lambda ()
                         (interactive)
                         (message "Inserting: textsc")
                         (insert "" "\\textsc{}")
                         (forward-char -1)
                         ))
(global-set-key "\C-ctV" '(lambda ()
                         (interactive)
			 (message "Inserting: Verbatim")
			 (insert "" "\\begin{Verbatim}\n\n\\end{Verbatim}")
			 (forward-line -1)
			 ))
(global-set-key "\C-ctv0" '(lambda ()
                         (interactive)
			 (message "Inserting: Verbatim")
			 (insert "" "\\begin{Verbatim}\n\n\\end{Verbatim}")
			 (forward-line -1)
			 ))
(global-set-key "\C-ctv1" '(lambda ()
                         (interactive)
			 (message "Inserting: Verbatim")
			 (insert "" "\\begin{Verbatim}\n  \n\\end{Verbatim}")
			 (forward-line -1)
			 (forward-char 2)
			 ))
(global-set-key "\C-ctv2" '(lambda ()
                         (interactive)
			 (message "Inserting: Verbatim")
			 (insert "" "\\begin{Verbatim}\n    \n\\end{Verbatim}")
			 (forward-line -1)
			(forward-char 4)
			 ))
(global-set-key "\C-ctvv" '(lambda ()
                         (interactive)
			 (message "Inserting: Verbatim[frame=single]")
			 (insert "" "\\begin{Verbatim}[frame=single]\n\n\\end{Verbatim}")
			 (forward-line -1)
			 ))
(global-set-key "\C-ctt" '(lambda ()
                         (interactive)
			 (message "Inserting: texttt")
			 (insert "" "\\texttt{}")
			 (forward-char -1)
			 ))
(global-set-key "\C-ctxe" '(lambda ()
                         (interactive)
			 (message "Inserting: emph")
			 (insert "" "\\emph{}")
			 (forward-char -1)
			 ))

;; mindenféle cucc, ami kapcsoszárójelet tartalmaz
(global-set-key "\C-ctss" '(lambda ()
                         (interactive)
			 (message "Inserting: scalar")
			 (insert "" "\\skalar{}{}")
			 (forward-char -3)
			 ))
(global-set-key "\C-ctsd" '(lambda ()
                         (interactive)
			 (message "Inserting: dfrac")
			 (insert "" "\\dfrac{}{}")
			 (forward-char -3)
			 ))
(global-set-key "\C-ctsf" '(lambda ()
                         (interactive)
			 (message "Inserting: frac")
			 (insert "" "\\frac{}{}")
			 (forward-char -3)
			 ))

;; egyéb cucc :)
(global-set-key "\C-ctfv" '(lambda ()
                         (interactive)
			 (message "Inserting: vektor")
			 (insert "" "\\vekt")
			 ))
(global-set-key "\C-ctfc" '(lambda ()
                         (interactive)
			 (message "Inserting: cdot")
			 (insert "" "\\cdot")
			 ))
(global-set-key "\C-ctf2" '(lambda ()
                         (interactive)
			 (message "Inserting: \"")
			 (insert "" "\"")

			 ))
(global-set-key "\C-ct\"" '(lambda ()
                         (interactive)
			 (message "Inserting: \"")
			 (insert "" "\"")
			 ))

;; könyv, stb részek (fejezet, etc)
(global-set-key "\C-cts1" '(lambda ()
                         (interactive)
			 (message "Inserting: PART")
			 (insert "" "\n\n\\part{}\n")
			 (forward-char -2)
			 ))
(global-set-key "\C-cts2" '(lambda ()
                         (interactive)
			 (message "Inserting: CHAPTER")
			 (insert "" "\n\n\\chapter{}\n")
			 (forward-char -2)
			 ))
(global-set-key "\C-cts3" '(lambda ()
                         (interactive)
			 (message "Inserting: SECTION")
			 (insert "" "\n\n\\section{}\n")
			 (forward-char -2)
			 ))
(global-set-key "\C-cts4" '(lambda ()
                         (interactive)
			 (message "Inserting: SUBSECTION")
			 (insert "" "\n\n\\subsection{}\n")
			 (forward-char -2)
			 ))
(global-set-key "\C-cts5" '(lambda ()
                         (interactive)
			 (message "Inserting: SubSubSECTION")
			 (insert "" "\n\n\\subsubsection{}\n")
			 (forward-char -2)
			 ))
(global-set-key "\C-cts6" '(lambda ()
                         (interactive)
			 (message "Inserting: PARAGRAPH")
			 (insert "" "\n\n\\paragraph{}")
			 (forward-char -1)
			 ))
;; par extra

(global-set-key "\C-ctx1" '(lambda ()
                         (interactive)
			 (message "Inserting: SUPERSET")
			 (insert "" "^{}")
			 (forward-char -1)
			 ))
(global-set-key "\C-ctx2" '(lambda ()
                         (interactive)
			 (message "Inserting: SUBSET")
			 (insert "" "_{}")
			 (forward-char -1)
			 ))
(global-set-key "\C-ctx3" '(lambda ()
                         (interactive)
			 (message "Inserting: POINT_0")
			 (insert "" "(x_0,y_0,z_0)")
			 ))
(global-set-key "\C-ctx4" '(lambda ()
                         (interactive)
			 (message "Inserting: PARTIAL")
			 (insert "" "\\partial")
			 ))
(global-set-key "\C-ctx5" '(lambda ()
                         (interactive)
			 (message "Inserting: F(u_0,v_0)")
			 (insert "" " F(u_0,v_0)")
			 ))
(global-set-key "\C-ctx6" '(lambda ()
                         (interactive)
			 (message "Inserting: ESF + par")
			 (insert "" "$\\F\\subset\\R^3$ ESF, $F\\colon \\I^2\\to\\R^3$ egy paraméterezése")
			 ))


;; Altalanos environment
(defun insert-environment (name)
    "Insert environment NAME"
    (interactive "sEnvironment name: ")
    (message "Inserting environment `%s'" name)
    (insert (format "\\begin{%s}\n\n\\end{%s}" name name))
    (forward-line -1)
    )


(global-set-key "\C-cte" 'insert-environment)
